language: c

compiler:
  - clang
  - gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq check libbz2-1.0 libev4 valgrind
  - wget https://bitbucket.org/despiegk/arakoon/downloads/arakoon_1.5.0_amd64.deb
  - sudo dpkg -i arakoon_1.5.0_amd64.deb
  - ./autogen.sh

env: ARAKOON_EXECUTABLE_NAME=/usr/bin/arakoon
